[project]
name = "practical-deep-learning-notes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastai>=2.8.5",
    "ipykernel>=7.1.0",
    "jupyter>=1.1.1",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
]
